//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dialogs.rc
//
#define IDD_ABOUT                       101
#define IDD_COMPILE                     102
#define IDD_LINK                        103
#define IDD_DIR                         104
#define IDB_BLUEGNU                     106
#define IDC_EDIT1                       1000
#define IDC_HOMEDIR                     1000
#define IDC_EDIT2                       1001
#define IDC_INCLUDEDIR                  1001
#define IDC_C_INCLUDE_PATH              1001
#define IDC_EDIT3                       1002
#define IDC_LIBDIR                      1002
#define IDGHELP_DIR                     1003
#define IDHELP_DIR                      1003
#define IDC_RADIO1                      1005
#define IDC_CONSOLE                     1005
#define IDC_RADIO2                      1006
#define IDC_WINDOWS                     1006
#define IDC_RADIO3                      1007
#define IDC_DLL                         1007
#define IDC_RADIO4                      1008
#define IDC_OPT3                        1008
#define IDC_CHECK1                      1009
#define IDC_CHECK2                      1010
#define IDC_SUPPORTANSI                 1010
#define IDC_RADIO5                      1012
#define IDC_OPTSIZE                     1012
#define IDC_CHECK4                      1013
#define IDC_DEBUG                       1013
#define IDHELP_COMPILE                  1014
#define IDHELP_LINK                     1016
#define IDC_CHECK3                      1017
#define IDC_CHECK5                      1018
#define IDC_CHECK6                      1019
#define IDC_PROFILE                     1021
#define IDC_SYNTAX                      1022
#define IDC_WARNANSI                    1023
#define IDC_ERRORANSI                   1024
#define IDC_ALLERRORS                   1025
#define IDC_INHIBITWARN                 1026
#define IDC_I386                        1028
#define IDC_I486                        1029
#define IDC_PENTIUM                     1030
#define IDC_PENTIUMPRO                  1031
#define IDC_Compiler_Options            1032
#define IDC_EXTRA_COMPILER_OPTIONS      1032
#define IDC_Link_Libraries              1033
#define IDC_EXTRA_LINKER_OPTIONS        1033
#define IDC_NOOPT                       1034
#define IDC_OPT1                        1035
#define IDC_OPT2                        1036
#define IDC_CPLUS_INCLUDE_PATH          1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
